export const Data = [
  {
    id: 1,
    name: "Megahana Foods",
    cuisines: "Biryani, North Indian, Asian",
    rating: 4.4,
    deliveryTime: "38 mins",
  },
  {
    id: 2,
    name: "Spice Delight",
    cuisines: "South Indian, Tandoori",
    rating: 4.2,
    deliveryTime: "25 mins",
  },
  {
    id: 3,
    name: "Taste of Punjab",
    cuisines: "Punjabi, Curries",
    rating: 4.6,
    deliveryTime: "30 mins",
  },
  {
    id: 4,
    name: "Golden Bowl",
    cuisines: "Chinese, Noodles",
    rating: 4.0,
    deliveryTime: "40 mins",
  },
  {
    id: 5,
    name: "Flavors of Kerala",
    cuisines: "Kerala, Seafood",
    rating: 4.5,
    deliveryTime: "35 mins",
  },
  {
    id: 6,
    name: "Sizzling Tandoor",
    cuisines: "Tandoori, Kebabs",
    rating: 4.3,
    deliveryTime: "28 mins",
  },
  {
    id: 7,
    name: "Delhi Darbar",
    cuisines: "North Indian, Mughlai",
    rating: 4.7,
    deliveryTime: "32 mins",
  },
  {
    id: 8,
    name: "Thai Spice",
    cuisines: "Thai, Stir-fry",
    rating: 4.1,
    deliveryTime: "45 mins",
  },
  {
    id: 9,
    name: "Coastal Catch",
    cuisines: "Seafood, Coastal",
    rating: 4.6,
    deliveryTime: "50 mins",
  },
  {
    id: 10,
    name: "Bengal Bites",
    cuisines: "Bengali, Sweets",
    rating: 4.2,
    deliveryTime: "33 mins",
  },
  {
    id: 11,
    name: "Masala Magic",
    cuisines: "Indian, Street Food",
    rating: 4.4,
    deliveryTime: "29 mins",
  },
  {
    id: 12,
    name: "Himalayan Kitchen",
    cuisines: "Nepali, Tibetan",
    rating: 4.3,
    deliveryTime: "37 mins",
  },
  {
    id: 13,
    name: "Royal Feast",
    cuisines: "Hyderabadi, Biryani",
    rating: 4.5,
    deliveryTime: "42 mins",
  },
  {
    id: 14,
    name: "Green Leaf",
    cuisines: "Vegan, Salads",
    rating: 4.0,
    deliveryTime: "30 mins",
  },
  {
    id: 15,
    name: "Chaat Corner",
    cuisines: "Chaat, Snacks",
    rating: 4.6,
    deliveryTime: "25 mins",
  },
  {
    id: 16,
    name: "Curry House",
    cuisines: "Indian, Curries",
    rating: 4.2,
    deliveryTime: "35 mins",
  },
  {
    id: 17,
    name: "Sushi Haven",
    cuisines: "Japanese, Sushi",
    rating: 4.7,
    deliveryTime: "40 mins",
  },
  {
    id: 18,
    name: "Rajasthani Rasoi",
    cuisines: "Rajasthani, Dal Baati",
    rating: 4.3,
    deliveryTime: "38 mins",
  },
  {
    id: 19,
    name: "Pizza Palazzo",
    cuisines: "Italian, Pizza",
    rating: 4.1,
    deliveryTime: "28 mins",
  },
  {
    id: 20,
    name: "Desi Dhaba",
    cuisines: "Punjabi, Dhaba Style",
    rating: 4.5,
    deliveryTime: "34 mins",
  },
  {
    id: 21,
    name: "Urban Tadka",
    cuisines: "North Indian, Grill",
    rating: 3.8,
    deliveryTime: "36 mins",
  },
  {
    id: 22,
    name: "Kolkata Kitchen",
    cuisines: "Bengali, Fish",
    rating: 4.1,
    deliveryTime: "31 mins",
  },
  {
    id: 23,
    name: "Wok n Roll",
    cuisines: "Chinese, Asian",
    rating: 3.5,
    deliveryTime: "39 mins",
  },
  {
    id: 24,
    name: "Tandoori Nights",
    cuisines: "Indian, BBQ",
    rating: 4.3,
    deliveryTime: "33 mins",
  },
  {
    id: 25,
    name: "Spice Fusion",
    cuisines: "Indo-Chinese, Fusion",
    rating: 3.9,
    deliveryTime: "40 mins",
  },
  {
    id: 26,
    name: "The Salad Bar",
    cuisines: "Healthy, Continental",
    rating: 4.0,
    deliveryTime: "27 mins",
  },
  {
    id: 27,
    name: "Cafe Aroma",
    cuisines: "Cafe, Beverages",
    rating: 3.7,
    deliveryTime: "22 mins",
  },
  {
    id: 28,
    name: "Bombay Chaatwala",
    cuisines: "Chaat, Street Food",
    rating: 4.4,
    deliveryTime: "26 mins",
  },
  {
    id: 29,
    name: "Andhra Spice",
    cuisines: "Andhra, Spicy",
    rating: 4.5,
    deliveryTime: "32 mins",
  },
  {
    id: 30,
    name: "MexiCasa",
    cuisines: "Mexican, Burritos",
    rating: 4.1,
    deliveryTime: "41 mins",
  },
  {
    id: 31,
    name: "Gongura Delight",
    cuisines: "Andhra, Pickles",
    rating: 3.6,
    deliveryTime: "29 mins",
  },
  {
    id: 32,
    name: "Taste of Tibet",
    cuisines: "Tibetan, Momos",
    rating: 4.3,
    deliveryTime: "36 mins",
  },
  {
    id: 33,
    name: "Paneer Point",
    cuisines: "Vegetarian, Paneer",
    rating: 4.2,
    deliveryTime: "31 mins",
  },
  {
    id: 34,
    name: "Fish Fry Factory",
    cuisines: "Seafood, Fried",
    rating: 3.9,
    deliveryTime: "44 mins",
  },
  {
    id: 35,
    name: "Roller Express",
    cuisines: "Kathi Roll, Fast Food",
    rating: 4.0,
    deliveryTime: "23 mins",
  },
  {
    id: 36,
    name: "Dosa District",
    cuisines: "South Indian, Dosa",
    rating: 4.1,
    deliveryTime: "30 mins",
  },
  {
    id: 37,
    name: "Sweet Symphony",
    cuisines: "Desserts, Bakery",
    rating: 3.8,
    deliveryTime: "27 mins",
  },
  {
    id: 38,
    name: "Midnight Curry",
    cuisines: "Indian, Late Night",
    rating: 3.5,
    deliveryTime: "48 mins",
  },
  {
    id: 39,
    name: "Biriyani Junction",
    cuisines: "Biryani, Hyderabadi",
    rating: 4.4,
    deliveryTime: "39 mins",
  },
  {
    id: 40,
    name: "Goan Curry House",
    cuisines: "Goan, Seafood",
    rating: 4.0,
    deliveryTime: "35 mins",
  },
];
