export const Data = [
  {
    id: 1,
    name: "Megahana Foods",
    cuisines: "Biryani, North Indian, Asian",
    rating: "4.4 stars",
    deliveryTime: "38 mins",
  },
  {
    id: 2,
    name: "Spice Delight",
    cuisines: "South Indian, Tandoori",
    rating: "4.2 stars",
    deliveryTime: "25 mins",
  },
  {
    id: 3,
    name: "Taste of Punjab",
    cuisines: "Punjabi, Curries",
    rating: "4.6 stars",
    deliveryTime: "30 mins",
  },
  {
    id: 4,
    name: "Golden Bowl",
    cuisines: "Chinese, Noodles",
    rating: "4.0 stars",
    deliveryTime: "40 mins",
  },
  {
    id: 5,
    name: "Flavors of Kerala",
    cuisines: "Kerala, Seafood",
    rating: "4.5 stars",
    deliveryTime: "35 mins",
  },
  {
    id: 6,
    name: "Sizzling Tandoor",
    cuisines: "Tandoori, Kebabs",
    rating: "4.3 stars",
    deliveryTime: "28 mins",
  },
  {
    id: 7,
    name: "Delhi Darbar",
    cuisines: "North Indian, Mughlai",
    rating: "4.7 stars",
    deliveryTime: "32 mins",
  },
  {
    id: 8,
    name: "Thai Spice",
    cuisines: "Thai, Stir-fry",
    rating: "4.1 stars",
    deliveryTime: "45 mins",
  },
  {
    id: 9,
    name: "Coastal Catch",
    cuisines: "Seafood, Coastal",
    rating: "4.6 stars",
    deliveryTime: "50 mins",
  },
  {
    id: 10,
    name: "Bengal Bites",
    cuisines: "Bengali, Sweets",
    rating: "4.2 stars",
    deliveryTime: "33 mins",
  },
  {
    id: 11,
    name: "Masala Magic",
    cuisines: "Indian, Street Food",
    rating: "4.4 stars",
    deliveryTime: "29 mins",
  },
  {
    id: 12,
    name: "Himalayan Kitchen",
    cuisines: "Nepali, Tibetan",
    rating: "4.3 stars",
    deliveryTime: "37 mins",
  },
  {
    id: 13,
    name: "Royal Feast",
    cuisines: "Hyderabadi, Biryani",
    rating: "4.5 stars",
    deliveryTime: "42 mins",
  },
  {
    id: 14,
    name: "Green Leaf",
    cuisines: "Vegan, Salads",
    rating: "4.0 stars",
    deliveryTime: "30 mins",
  },
  {
    id: 15,
    name: "Chaat Corner",
    cuisines: "Chaat, Snacks",
    rating: "4.6 stars",
    deliveryTime: "25 mins",
  },
  {
    id: 16,
    name: "Curry House",
    cuisines: "Indian, Curries",
    rating: "4.2 stars",
    deliveryTime: "35 mins",
  },
  {
    id: 17,
    name: "Sushi Haven",
    cuisines: "Japanese, Sushi",
    rating: "4.7 stars",
    deliveryTime: "40 mins",
  },
  {
    id: 18,
    name: "Rajasthani Rasoi",
    cuisines: "Rajasthani, Dal Baati",
    rating: "4.3 stars",
    deliveryTime: "38 mins",
  },
  {
    id: 19,
    name: "Pizza Palazzo",
    cuisines: "Italian, Pizza",
    rating: "4.1 stars",
    deliveryTime: "28 mins",
  },
  {
    id: 20,
    name: "Desi Dhaba",
    cuisines: "Punjabi, Dhaba Style",
    rating: "4.5 stars",
    deliveryTime: "34 mins",
  },
];
